// song-list.js
export const songs = [
    { id: 1, name: "Turn down for what", artist: "DJ Snake, Lil Jon", year: 2013, url: "songs/Turn Down for What.m4a" },
    { id: 2, name: "Jump around", artist: "House of Pain", year: 1992, url: "songs/Jump Around.mp3" },
    { id: 3, name: "24k magic", artist: "Bruno Mars", year: 2016, url: "songs/24K Magic.m4a" },
    { id: 4, name: "We like to party", artist: "Vengaboys", year: 1998, url: "songs/We Like to Party! (the Vengabus).m4a" },
    { id: 5, name: "All the Small Things", artist: "Blink 182", year: 1999, url: "songs/All the Small Things.mp3" },
    { id: 6, name: "One More Time", artist: "Daft Punk", year: 2000, url: "songs/Daft Punk - One More Time.mp3" },
    { id: 7, name: "Dreams", artist: "Fleetwood Mac", year: 1977, url: "songs/Fleetwood Mac - Dreams - 2004 Remastered Edition.mp3" },
    { id: 8, name: "Starships", artist: "Nicki Minaj", year: 2012, url: "songs/Nicki_Minaj-Starships-DJ_Intro___DJ_Outro_Clean 2.mp3" },
    { id: 9, name: "The Real Slim Shady", artist: "Eminem", year: 2000, url: "songs/The Real Slim Shady (DJ SLICK Extended Mi.mp3" },
    { id: 10, name: "Titanium", artist: "David Guetta & Sia", year: 2011, url: "songs/Titanium (Feat. Sia).mp3" },
    { id: 11, name: "Untouched", artist: "The Veronicas", year: 2007, url: "songs/Untouched.m4a" },
    { id: 12, name: "Sandstorm", artist: "Darude", year: 1999, url: "songs/(darude) sandstorm (original mix).mp3" },
    { id: 13, name: "Baby", artist: "Justin Bieber feat. Ludacris", year: 2010, url: "songs/Baby (DJ SLICK Extended Mix).mp3" },
    { id: 14, name: "Blame it on the Boogie", artist: "The Jacksons", year: 1978, url: "songs/Blame it on the Boogie.m4a" },
    { id: 15, name: "Celebration", artist: "Kool & the Gang", year: 1980, url: "songs/Celebration.mp3" },
    { id: 16, name: "Crank That", artist: "Soulja Boy Tell 'Em", year: 2007, url: "songs/Crank That (Soulja Boy).m4a" },
    { id: 17, name: "Dancing Queen", artist: "ABBA", year: 1976, url: "songs/Dancing Queen.m4a" },
    { id: 18, name: "Freaks", artist: "Timmy Trumpet & Savage", year: 2014, url: "songs/Freaks (Radio Edit).m4a" },
    { id: 19, name: "Good Vibrations", artist: "The Beach Boys", year: 1966, url: "songs/Good Vibrations.m4a" },
    { id: 20, name: "Ice Ice Baby", artist: "Vanilla Ice", year: 1990, url: "songs/Ice Ice Baby.mp3" },
    { id: 21, name: "Jenny from the Block", artist: "Jennifer Lopez", year: 2002, url: "songs/Jenny from the Block.m4a" },
    { id: 22, name: "Just Dance", artist: "Lady Gaga", year: 2008, url: "songs/Just Dance.m4a" },
    { id: 23, name: "Levels", artist: "Avicii", year: 2011, url: "songs/Levels.m4a" },
    { id: 24, name: "Love Story", artist: "Taylor Swift", year: 2008, url: "songs/Love Story.mp3" },
    { id: 25, name: "Shake It Off", artist: "Taylor Swift", year: 2014, url: "songs/Shake It Off.m4a" },
    { id: 26, name: "Wannabe", artist: "Spice Girls", year: 1996, url: "songs/Spice Girls - Wannabe.mp3" },
    { id: 27, name: "Teenage Dirtbag", artist: "Wheatus", year: 2000, url: "songs/Teenage Dirtbag.mp3" },
    { id: 28, name: "Life Is A Highway", artist: "Tom Cochrane", year: 1991, url: "songs/Tom Cochrane - Life Is A Highway.mp3" },
    { id: 29, name: "Tour", artist: "Macky Gee", year: 2017, url: "songs/Tour.m4a" },
    { id: 30, name: "Uptown Girl", artist: "Billy Joel", year: 1983, url: "songs/Uptown Girl.mp3" },
    { id: 31, name: "We Are Family", artist: "Sister Sledge", year: 1979, url: "songs/We Are Family.mp3" },
    { id: 32, name: "Yeah 3x", artist: "Chris Brown", year: 2011, url: "songs/Yeah 3x.mp3" }
];