// song-list.js
export const songs = [
    { id: 1, name: "Turn down for what", artist: "DJ Snake, Lil Jon", year: 2013, difficulty: "Hard", url: "songs/Turn Down for What.m4a" },
    { id: 2, name: "Jump around", artist: "House of Pain", year: 1992, difficulty: "Hard", url: "songs/Jump Around.mp3" },
    { id: 3, name: "24k magic", artist: "Bruno Mars", year: 2016, difficulty: "Hard", url: "songs/24K Magic.m4a" },
    { id: 4, name: "We like to party", artist: "Vengaboys", year: 1998, difficulty: "Hard", url: "songs/We Like to Party! (the Vengabus).m4a" },
    { id: 5, name: "All the Small Things", artist: "Blink 182", year: 1999, difficulty: "Hard", url: "songs/All the Small Things.mp3" },
    { id: 6, name: "One More Time", artist: "Daft Punk", year: 2000, difficulty: "Hard", url: "songs/Daft Punk - One More Time.mp3" },
    { id: 7, name: "Dreams", artist: "Fleetwood Mac", year: 1977, difficulty: "Hard", url: "songs/Fleetwood Mac - Dreams - 2004 Remastered Edition.mp3" },
    { id: 8, name: "Starships", artist: "Nicki Minaj", year: 2012, difficulty: "Hard", url: "songs/Nicki_Minaj-Starships-DJ_Intro___DJ_Outro_Clean 2.mp3" },
    { id: 9, name: "The Real Slim Shady", artist: "Eminem", year: 2000, difficulty: "Hard", url: "songs/The Real Slim Shady (DJ SLICK Extended Mi.mp3" },
    { id: 10, name: "Titanium", artist: "David Guetta & Sia", year: 2011, difficulty: "Hard", url: "songs/Titanium (Feat. Sia).mp3" },
    { id: 11, name: "Untouched", artist: "The Veronicas", year: 2007, difficulty: "Hard", url: "songs/Untouched.m4a" },
    { id: 12, name: "Sandstorm", artist: "Darude", year: 1999, difficulty: "Hard", url: "songs/(darude) sandstorm (original mix).mp3" },
    { id: 13, name: "Baby", artist: "Justin Bieber feat. Ludacris", year: 2010, difficulty: "Hard", url: "songs/Baby (DJ SLICK Extended Mix).mp3" },
    { id: 14, name: "Blame it on the Boogie", artist: "The Jacksons", year: 1978, difficulty: "Hard", url: "songs/Blame it on the Boogie.m4a" },
    { id: 15, name: "Celebration", artist: "Kool & the Gang", year: 1980, difficulty: "Hard", url: "songs/Celebration.mp3" },
    { id: 16, name: "Crank That", artist: "Soulja Boy Tell 'Em", year: 2007, difficulty: "Hard", url: "songs/Crank That (Soulja Boy).m4a" },
    { id: 17, name: "Dancing Queen", artist: "ABBA", year: 1976, difficulty: "Easy", url: "songs/Dancing Queen.m4a" },
    { id: 18, name: "Freaks", artist: "Timmy Trumpet & Savage", year: 2014, difficulty: "Hard", url: "songs/Freaks (Radio Edit).m4a" },
    { id: 19, name: "Good Vibrations", artist: "The Beach Boys", year: 1966, difficulty: "Hard", url: "songs/Good Vibrations.m4a" },
    { id: 20, name: "Ice Ice Baby", artist: "Vanilla Ice", year: 1990, difficulty: "Hard", url: "songs/Ice Ice Baby.mp3" },
    { id: 21, name: "Jenny from the Block", artist: "Jennifer Lopez", year: 2002, difficulty: "Hard", url: "songs/Jenny from the Block.m4a" },
    { id: 22, name: "Just Dance", artist: "Lady Gaga", year: 2008, difficulty: "Hard", url: "songs/Just Dance.m4a" },
    { id: 23, name: "Levels", artist: "Avicii", year: 2011, difficulty: "Hard", url: "songs/Levels.m4a" },
    { id: 24, name: "Love Story", artist: "Taylor Swift", year: 2008, difficulty: "Hard", url: "songs/Love Story.mp3" },
    { id: 25, name: "Shake It Off", artist: "Taylor Swift", year: 2014, difficulty: "Hard", url: "songs/Shake It Off.m4a" },
    { id: 26, name: "Wannabe", artist: "Spice Girls", year: 1996, difficulty: "Hard", url: "songs/Spice Girls - Wannabe.mp3" },
    { id: 27, name: "Teenage Dirtbag", artist: "Wheatus", year: 2000, difficulty: "Hard", url: "songs/Teenage Dirtbag.mp3" },
    { id: 28, name: "Life Is A Highway", artist: "Tom Cochrane", year: 1991, difficulty: "Hard", url: "songs/Tom Cochrane - Life Is A Highway.mp3" },
    { id: 29, name: "Tour", artist: "Macky Gee", year: 2017, difficulty: "Hard", url: "songs/Tour.m4a" },
    { id: 30, name: "Uptown Girl", artist: "Billy Joel", year: 1983, difficulty: "Hard", url: "songs/Uptown Girl.mp3" },
    { id: 31, name: "We Are Family", artist: "Sister Sledge", year: 1979, difficulty: "Hard", url: "songs/We Are Family.mp3" },
    { id: 32, name: "Yeah 3x", artist: "Chris Brown", year: 2011, difficulty: "Hard", url: "songs/Yeah 3x.mp3" },
    { id: 33, name: "December 1963", artist: "The Four Seasons", year: 1975, difficulty: "Medium", url: "songs/10 December 1963 (Oh What a Night).mp3" },
    { id: 34, name: "Mamma Mia", artist: "ABBA", year: 1975, difficulty: "Easy", url: "songs/ABBA - Mamma Mia.mp3" },
    { id: 35, name: "Are You Gonna Be My Girl", artist: "Jet", year: 2003, difficulty: "Hard", url: "songs/Are You Gonna Be My Girl.mp3" },
    { id: 36, name: "Believe", artist: "Cher", year: 1998, difficulty: "Easy", url: "songs/Believe.mp3" },
    { id: 37, name: "Cake By The Ocean", artist: "DNCE", year: 2015, difficulty: "Medium", url: "songs/Cake_By_The_Ocean.mp3" },
    { id: 38, name: "Cheap Wine", artist: "Cold Chisel", year: 1980, difficulty: "Medium", url: "songs/Cheap Wine.mp3" },
    { id: 39, name: "Copperhead Road", artist: "Steve Earle", year: 1988, difficulty: "Medium", url: "songs/Copperhead Road.mp3" },
    { id: 40, name: "Cosmic Girl", artist: "Jamiroquai", year: 1996, difficulty: "Medium", url: "songs/Cosmic Girl.m4a" },
    { id: 41, name: "Crazy In Love", artist: "Beyonce feat. Jay-Z", year: 2003, difficulty: "Easy", url: "songs/Crazy In Love (DJ JOHNIBOI EXTENDED MIX).mp3" },
    { id: 42, name: "Groove Is In the Heart", artist: "Deee-Lite", year: 1990, difficulty: "Easy", url: "songs/Deee-Lite - Groove Is In The Heart.mp3" },
    { id: 43, name: "Disturbia", artist: "Rihanna", year: 2008, difficulty: "Easy", url: "songs/Disturbia.m4a" },
    { id: 44, name: "Don't You Worry Child", artist: "Swedish House Mafia", year: 2012, difficulty: "Medium", url: "songs/Don't You Worry Child (Radio Edit) [feat. John Martin].m4a" },
    { id: 45, name: "September", artist: "Earth Wind & Fire", year: 1999, difficulty: "Medium", url: "songs/Earth Wind and Fire - September 99 (phats an.mp3" },
    { id: 46, name: "Fantasy", artist: "Mariah Carey", year: 1995, difficulty: "Medium", url: "songs/Fantasy (Intro - Clean).mp3" },
    { id: 47, name: "Feel So Close", artist: "Calvin Harris", year: 2011, difficulty: "Medium", url: "songs/Feel So Close [Radio Edit].m4a" },
    { id: 48, name: "Flaunt It", artist: "TV Rock", year: 2006, difficulty: "Medium", url: "songs/Flaunt It (Radio Edit) 2.m4a" },
    { id: 49, name: "Heaven Is A Place On Earth", artist: "Belinda Carlisle", year: 1987, difficulty: "Medium", url: "songs/Heaven Is A Place On Earth.mp3" },
    { id: 50, name: "Hot N Cold", artist: "Katy Perry", year: 2008, difficulty: "Medium", url: "songs/Hot N Cold.m4a" },
    { id: 51, name: "I Like to Move It", artist: "Reel 2 Real", year: 1994, difficulty: "Medium", url: "songs/I like to move it.mp3" },
    { id: 52, name: "I Wanna Dance With Somebody", artist: "Whitney Houston", year: 1987, difficulty: "Easy", url: "songs/I Wanna Dance With Somebody.mp3" },
    { id: 53, name: "I Will Survive", artist: "Gloria Gaynor", year: 1978, difficulty: "Easy", url: "songs/I Will Survive.m4a" },
    { id: 54, name: "Nutbush City Limits", artist: "Ike & Tina Turner", year: 1973, difficulty: "Medium", url: "songs/Ike & Tina Turner - Nutbush City Limits.mp3" },
    { id: 55, name: "Insomnia", artist: "Faithless", year: 1995, difficulty: "Medium", url: "songs/Insomnia.m4a" },
    { id: 56, name: "Macarena", artist: "Los Del Rio", year: 1993, difficulty: "Medium", url: "songs/Los Del Rio - Macarena.mp3" },
    { id: 57, name: "Love Generation", artist: "Bob Sinclar", year: 2005, difficulty: "Medium", url: "songs/Love Generation.mp3" },
    { id: 58, name: "MMM Bop", artist: "Hanson", year: 1997, difficulty: "Medium", url: "songs/Mmbop (DJ JAY MMP Intro).mp3" },
    { id: 59, name: "Mr Brightside", artist: "The Killers", year: 2003, difficulty: "Easy", url: "songs/Mr Brightside.mp3" },
    { id: 60, name: "My Delirium", artist: "Ladyhawke", year: 2008, difficulty: "Medium", url: "songs/My Delirium.m4a" },
    { id: 61, name: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987, difficulty: "Easy", url: "songs/Never Gonna Give You Up.mp3" },
    { id: 62, name: "No Diggity", artist: "Blackstreet feat. Dr. Dre", year: 1996, difficulty: "Medium", url: "songs/No Diggity (DJ SLICK Extended Mix).mp3" },
    { id: 63, name: "No Scrubs", artist: "TLC", year: 1999, difficulty: "Medium", url: "songs/No Scrubs (DJ SLICK Extended Mix).mp3" },
    { id: 64, name: "Fireball", artist: "Pitbull feat. John Ryan", year: 2014, difficulty: "Medium", url: "songs/Pitbull_ft._John_ryan-Fireball-DJ_Intro___DJ_Outro_1_Clean.mp3" },
    { id: 65, name: "Pony", artist: "Ginuwine", year: 1996, difficulty: "Medium", url: "songs/Pony (MMP Intro) (Clean).mp3" },
    { id: 66, name: "Praise You", artist: "Fatboy Slim", year: 1999, difficulty: "Medium", url: "songs/Praise You (Radio Edit).m4a" },
    { id: 67, name: "Under Pressure", artist: "Queen", year: 1981, difficulty: "Easy", url: "songs/Queen - Under Pressure - Remastered 2011.mp3" },
    { id: 68, name: "Rehab", artist: "Amy Winehouse", year: 2006, difficulty: "Easy", url: "songs/Rehab.m4a" },
    { id: 69, name: "Return Of The Mack", artist: "Mark Morrison", year: 1996, difficulty: "Medium", url: "songs/Return Of The Mack.mp3" },
    { id: 70, name: "Run to Paradise", artist: "Nick Skitz", year: 1988, difficulty: "Medium", url: "songs/Run To Paradise.mp3" },
    { id: 71, name: "SexyBack", artist: "Justin Timberlake", year: 2006, difficulty: "Easy", url: "songs/SexyBack.m4a" },
    { id: 72, name: "Shackles", artist: "Mary Mary", year: 2000, difficulty: "Easy", url: "songs/Shackles (Praise You) (SmItLeR Extended).mp3" },
    { id: 73, name: "Shake It", artist: "Metro Station", year: 2008, difficulty: "Medium", url: "songs/Shake It.m4a" },
    { id: 74, name: "Show Me Love", artist: "Robin S.", year: 1990, difficulty: "Medium", url: "songs/Show Me Love.m4a" },
    { id: 75, name: "Sweet Dreams", artist: "La Bouche", year: 1994, difficulty: "Medium", url: "songs/Sweet Dreams.m4a" },
    { id: 76, name: "Take On Me", artist: "a-ha", year: 1985, difficulty: "Easy", url: "songs/Take On Me.mp3" },
    { id: 77, name: "Tequila", artist: "Alt and The Lost Civilization", year: 1988, difficulty: "Medium", url: "songs/Tequila.m4a" },
    { id: 78, name: "The Reflex", artist: "Duran Duran", year: 1983, difficulty: "Medium", url: "songs/The Reflex.m4a" },
    { id: 79, name: "Uptown Funk", artist: "Mark Ronson feat. Bruno Mars", year: 2014, difficulty: "Easy", url: "songs/Uptown Funk (SmItLeR Extended).mp3" },
    { id: 80, name: "Whip It", artist: "Devo", year: 1980, difficulty: "Medium", url: "songs/Whip It.m4a" }
];
